apiVersion: v1
kind: Service
metadata:
  name: training-component-service
  namespace: kubeflow
  labels:
    app: training-component
spec:
  selector:
    app: training-component
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
  type: ClusterIP
